language: objective

compiler:
 - gcc

env:
  matrix:
    #- CXX11=true TARGET=build_osmium
    #- CXX11=true TARGET=build_osrm QUIET=true
    #- CXX11=false TARGET=build_osrm QUIET=true
    #- CXX11=true TARGET=build_mapnik PUBLISH=true QUIET=true
    #- CXX11=false TARGET=build_mapnik PUBLISH=true QUIET=true
    #- CXX11=false TARGET=build_osm2pgsql QUIET=true
    #- CXX11=false TARGET=build_liblas QUIET=true
    - CXX11=false TARGET=build_http QUIET=true
  global:
    - secure: jLa/ai9FzqYRZkZrjQhn5KbsSrDDLBV2hPlKQh/nMn5bb5RooMnAo/9aSYsq8o4lMtnqsYX7wv/r35GKpJJk1OFBWmj1L94KTfm1TdC5Xlr5iumRbQ9VEPBbMgQw6WU+bp88QxvT0I9DZxgciMk6GV9eBM3dH4BSIwRCamOl018=
    - secure: iQ5aDVTqRYX8YQdxi8gk0jLoNtWvtb7x3ZQORQT9w+y/X4qX+5mV/FV88BQBYF4MMlF5ePGx8IItpEagllIZboAf68CBvclretlPXUiw3JyHaALfHJI1n02y/j/NnY2P3QJUG9QuFBdIAeUWUyReGxOD9Bhcj4E8nHkAgDNsz5k=

before_install:
 - if [[ `uname -s` == 'Darwin' ]]; then vm_stat && sysctl -n hw.memsize; else free; fi

install:
 - true

before_script:
 - true

script:
 - source ./build.sh
 - export PLATFORM=${TRAVIS_BRANCH}
 - ${TARGET}